food/urls.py
from django.urls import path

from . import views

app_name = 'food'

urlpatterns = [
    path("contact/", views.contact, name="contact"),
    path("pizza/", views.pizza, name="pizza"),
    path("burgers/", views.burgers, name="burgers"),
]

snack/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views


urlpatterns = [
    path("", views.index, name="index"),
    path("food/", include("food.urls", namespace="food")),
    path('admin/', admin.site.urls),
]

food/models.py
from django.db import models
from cloudinary.models import CloudinaryField

# Create your models here.
class Pizza(models.Model):
    nom = models.CharField(max_length=255)
    prixm = models.DecimalField(max_digits=5, decimal_places=2)
    prixl = models.DecimalField(max_digits=5, decimal_places=2)
    descf = models.TextField()
    descb = models.TextField() 
    pimage = CloudinaryField('image')

class Burger(models.Model):
    nom = models.CharField(max_length=255)
    prixm = models.DecimalField(max_digits=5, decimal_places=2)
    prixl = models.DecimalField(max_digits=5, decimal_places=2)
    descf = models.TextField()
    descb = models.TextField() 
    bimage = CloudinaryField('image')

food/views.py
from django.shortcuts import render
from .models import Pizza, Burger

# Create your views here.
def index(request):
    ctx = {'active_tab': 'tab1'}
    return render(request, 'food/index.html', ctx)

def contact(request):
    ctx = {'active_tab': 'tab5'}
    return render(request, 'food/contact.html', ctx)

def pizza(request):
    pizzas = Pizza.objects.all()
    ctx = {'active_tab': 'tab2', 'pizzas':pizzas}
    return render(request, 'food/pizza.html', ctx)

def burgers(request):
    burgers = Burger.objects.all()
    ctx = {'active_tab': 'tab3', 'burgers':burgers}
    return render(request, 'food/burgers.html', ctx)

food/templates/food/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load staticfiles %}

  <link rel="stylesheet" type="text/css" href="{% static 'food/css/bootstrap.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'food/css/style.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'food/css/aos.css' %}" />
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar fixed-top  navbar-dark" id="mynav">
      <a class="navbar-brand" href="{% url 'index' %}">
          <img src="https://img.icons8.com/cotton/32/000000/hamburger.png"> <span style="color: rgb(25, 248, 92)">
              M</span>ajin <span style="color: rgb(24, 211, 80)">B</span>urgers
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <a class="nav-link {% if active_tab == 'tab1' %} active{% endif %}" href="{% url 'index' %}">Acceuil</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if active_tab == 'tab2' %} active{% endif %}" href="{% url 'food:pizza' %}">Pizza</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link {% if active_tab == 'tab3' %} active{% endif %}" href="{% url 'food:burgers' %}">Burgers</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="#">Dessert</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link {% if active_tab == 'tab5' %} active{% endif %}" href="{% url 'food:contact' %}">Contact</a>
              </li>
          </ul>
      </div>
  </nav>

    <div class="container-fluid" style="padding-bottom: 50px;">
        <div class="row">
          <div class="box">
            {% block content %}{% endblock %}
          </div>
        </div>
    </div>
      
    <footer style="padding-top:20px;">
      <div class="container-fluid">
           <div class="row" style="padding-left:50px; padding-top:20px; padding-bottom:10px;">

                <div class="col-md-6 col-sm-6">
                     <div class="footer-thumb"> 
                          <h4 class="pb-2">Contact Info</h4>
                          <p>Vous pouvez nous contacter par téléphone ou par email:</p>

                          <div class="contact-info">
                               <p><img src="https://img.icons8.com/cute-clipart/26/000000/cell-phone.png">&nbsp 07-81-05-76-04</p>
                               <p><img src="https://img.icons8.com/dusk/26/000000/email.png">&nbsp merazig.webdev@gmail.com</p>
                               <p><img src="https://img.icons8.com/bubbles/26/000000/order-delivered.png"> 400 Cours Emile Zola<br>
                                  &nbsp &nbsp &nbsp &nbsp 69100 Villeurbanne</p>
                          </div>
                     </div>
                </div>

    

                <div class="col-md-6 col-sm-6"> 
                     <div class="footer-thumb">
                          <div class="opening-hours">
                               <h4 class="pb-2">Horaires d'ouverture</h4>
                               <p>Lundi - Vendredi: <span>08H00 - 20H00</span></p>
                               <p>Samedi: <span>09H00 - 13H00</span></p>
                               <p>Dimanche: <span>Fermé</span></p>
                          </div> 

                          <ul class="list-inline">
                               <li class="list-inline-item"><a href="#"><img src="https://img.icons8.com/color/32/000000/facebook.png"></a></li>
                               <li class="list-inline-item"><a href="#"><img src="https://img.icons8.com/color/32/000000/twitter-squared.png"></a></li>
                               <li class="list-inline-item"><a href="#"><img src="https://img.icons8.com/color/32/000000/instagram-new.png"></a></li>
                          </ul>
                     </div>
                </div>

                <div class="col-md-12 col-sm-12 border-top">
                            <div class="text-center"> 
                                 <p class="text-center pt-4">Copyright &copy; 2019 The Majin Dev 
                                 
                                 | Design: merazig</a></p>
                            </div>
                  </div>
                
           </div>
      </div>
 </footer>
    <script src="{% static 'food/js/aos.js' %}"></script>

    <!-- jQuery -->
    <script src="{% static 'food/js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'food/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'food/js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'food/js/main.js' %}"></script>
    </body>
</html>

food/templates/food/burgers.html
{% extends 'food/base.html' %}

{% block title %}Burgers{% endblock %}

{% block content %}

{% load cloudinary %}

<div id="demo" class="carousel slide" data-ride="carousel" style="box-shadow: 0px 5px 10px">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1571150642/food/burg_ogtyfk.jpg" alt="slider1">
        <div class="carousel-caption">
          <h3 style="color: whitesmoke;">Majin Burgers</h3>
          <p>Nos Burgers</p>
        </div>   
      </div>
    </div>
</div>
<div class="container p-4">
  <h2 class="text-center">~ Nos Burgers ~</h2>
  <h4 class="text-center pb-2" style="color: rgb(43, 41, 41)">⊰ ∼∼.∼∼ ⊱</h4>

  
  <div class="row pt-4">
      {% for burger in burgers %}
    <div class="col-xs-12 col-sm-6 col-md-4" data-aos="zoom-in">
        <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
            <div class="mainflip p-3">
                <div class="frontside">
                    <div class="card">
                        <div class="card-body text-center">
                            <p><img class=" img-fluid" src='{{ burger.bimage.url }}' alt="card image"></p>
                            <h4 class="card-title">{{ burger.nom }}</h4>
                            <p class="card-text">{{ burger.descf }}</p>
                            <h5>Seul: {{ burger.prixm }} €  Menu: {{ burger.prixl }} €</h5>
                        </div>
                    </div>
                </div>
                <div class="backside p-3">
                    <div class="card">
                        <div class="card-body text-center">
                            <h4 class="card-title">{{ burger.nom }}</h4>
                            <p class="card-text">{{ burger.descb }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  {% endfor %}
  </div>
  
</div>

{% endblock %}

food/templates/food/contact.html
{% extends 'food/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}

<div id="demo" class="carousel slide" data-ride="carousel" style="box-shadow: 0px 5px 10px">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570113925/food/place_vfm7xt.jpg" alt="slider1">
        <div class="carousel-caption">
          <h3 style="color: whitesmoke;">Majin Burgers</h3>
          <p>Commander</p>
        </div>   
      </div>
    </div>
</div>

<div class="container p-4">
    <h2 class="text-center">~ Majin Burgers ~</h2>
    <h4 class="text-center pb-4" style="color: rgb(43, 42, 42)">⊰ ∼∼.∼∼ ⊱</h4>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-4 p-1">
            <br>
            <p class="par">Rendez-vous au The Restaurant pour déguster nos plats. Si vous souhaitez reserver 
                une table, vous pouvez nous contacter par email ou téléphone.</p>
            <p>Vous pouvez commander via une plateforme partenaire</p>
            <ul class="list-inline text-center">
                <li class="list-inline-item p-2"><img src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570115088/food/uber_j4uswu.png" class="img rounded" height="50px" width="50px"></li>
                <li class="list-inline-item p-2"><img src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570115089/food/deliveroo_m6cdtc.png" class="img rounded" height="50px" width="50px"></li>
                <li class="list-inline-item p-2"><img src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570115088/food/just_zmwhej.jpg" class="img rounded" height="50px" width="50px"></li>
            </ul>
            <p>Un autre modèle de site pour Restaurant:</p>
            <p><a href="https://lerestaurant.netlify.com/" target="_blank">lerestaurant.netifly.com</a></p>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-5 bg" data-aos="fade-up">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1391.4732141096401!2d4.878310658069345!3d45.77226386565072!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDXCsDQ2JzIwLjEiTiA0wrA1Mic0NS45IkU!5e0!3m2!1sfr!2sfr!4v1563445380037!5m2!1sfr!2sfr"
                width="100%" height="350" frameborder="0" style="border:0; box-shadow: 5px 5px 5px #888888;" allowfullscreen></iframe>
        </div>
        <div class="col-md-1"></div>

    </div>

</div>
<div class="container-fluid p-4">
<div class="row">
    <div class="col-md-3">
        <img class="img-fluid voir" src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1564901937/food/photo-1414235077428-338989a2e8c0_tb8nv9.jpg" data-toggle="modal" data-target="#myModal">
    </div>
    <div class="col-md-3">
        <img class="img-fluid voir" src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1564901930/food/pexels-photo-723031_ays62y.jpg" data-toggle="modal" data-target="#myModal2">
    </div>
    <div class="col-md-3">
        <img class="img-fluid voir" src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570115473/food/g1_izhc7l.jpg" data-toggle="modal" data-target="#myModal3">
    </div>
    <div class="col-md-3">
        <img class="img-fluid voir" src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570115473/food/g4_bg4z6c.jpg" data-toggle="modal" data-target="#myModal4">
    </div>
</div>
<div class="modal" id="myModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

    <!-- Modal body -->
        <div class="modal-body">
            <img class="img-fluid" src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1564901937/food/photo-1414235077428-338989a2e8c0_tb8nv9.jpg">
        </div>
    
        </div>
    </div>
</div>
<div class="modal" id="myModal2">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

    <!-- Modal body -->
        <div class="modal-body">
            <img class="img-fluid" src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1564901930/food/pexels-photo-723031_ays62y.jpg">
        </div>
    
        </div>
    </div>
</div>
<div class="modal" id="myModal3">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

    <!-- Modal body -->
        <div class="modal-body">
            <img class="img-fluid" src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570115473/food/g1_izhc7l.jpg">
        </div>
    
        </div>
    </div>
</div>
<div class="modal" id="myModal4">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

    <!-- Modal body -->
        <div class="modal-body">
            <img class="img-fluid" src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570115473/food/g4_bg4z6c.jpg">
        </div>
    
        </div>
    </div>
</div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

{% block title %}Merazig Food{% endblock %}

{% block content %}
<div id="demo" class="carousel slide" data-ride="carousel" style="box-shadow: 0px 5px 10px">
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>
      <li data-target="#demo" data-slide-to="1"></li>
      <li data-target="#demo" data-slide-to="2"></li>
    </ul>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://res.cloudinary.com/dxflxf2nv/image/upload/c_scale,h_806,q_80,w_1600/v1569179683/food/pexels-photo-416594_aocmu1.jpg" alt="slider1" >
        <div class="carousel-caption">
          <h3>Nos Burgers</h3>
          <p>We had such a great time in LA!</p>
        </div>   
      </div>
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1569179742/food/Slider_ifzbgl.jpg" alt="Chicago">
        <div class="carousel-caption">
          <h3><a class="stretched-link" href="pizza.html">Majin Burgers</a></h3>
          <p>Nos Pizza</p>
        </div>   
      </div>
      <div class="carousel-item">
        <img src="https://res.cloudinary.com/dxflxf2nv/image/upload/c_scale,h_806,w_1600/v1569180976/food/des_ksgmef.jpg" alt="New York">
        <div class="carousel-caption">
          <h3>Majin Burgers</h3>
          <p>We love the Big Apple!</p>
        </div>   
      </div>
    </div>
</div>
<div class="container-fluid p-4">
    <h1 class="text-center pt-3" style="color: rgba(83, 18, 18, 0.8);">The Majin Burgers</h1>
    <div class="row pt-4">
      <div class="col-md-1"></div>
      <div class="col-md-5 p-1 text-justify">
          <br>
          <h4>A propos</h4>
          <br>
          <p class="pr-3">C'est un site web pour les restaurants. Si vous souhaitez avoir un site web pour
              présenter votre activité, vous pouvez me contacter par email ou téléphone.</p>
          <p class="pr-3">Vous trouvez mon email et mon téléphone en bas de chaque page.</p>
          <p>Un autre modèle de site pour Restaurant:</p>
          <p><a href="https://lerestaurant.netlify.com/" target="_blank">lerestaurant.netifly.com</a></p>
      </div>
      <div class="col-md-5 p-2 pb-4" data-aos="flip-left">
          <img class="img-fluid bg-light" src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1569182715/food/chairs-city-lunch-6458_ciqhug.jpg" style="box-shadow: 5px 5px 5px">
      </div>
      <div class="col-md-1"></div>
    </div> 
</div>

<div class="container-fluid p-4 bg-light">
  <br>
  <h2 class="text-center">~ Nos spécialités ~</h2>
  <br>
  <section class="carte">
  <div class="row text-center m-2">
          <div class="col-md-4 p-2" data-aos="flip-up">
            <div class="rounded m-1 bg-white">
                <h4>Burgers</h4>
                <img src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1564901933/food/pexels-photo-1600727_1_osudt9.jpg" class="img-fluid rounded-circle m-2 w-50" style="box-shadow: 5px 5px 5px #555252;"/>
                <p style="padding: 20px;">Viande provenant d'animaux nés, élevés, 
                    abattus, découpés et transformés en France.</p>
            </div>
          </div>

          <div class="col-md-4 p-2" data-aos="flip-left">
              <div class="rounded m-1 bg-white">
                  <h4>Pizzas</h4>
                  <img src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570113037/food/pizza_sj8bmr.jpg" class="img-fluid rounded-circle m-2 w-50" style="box-shadow: 5px 5px 5px #555252;"/>
                  <p style="padding: 20px;">Nos pizzas sont préparés avec des produits frais et locaux</p>
              </div>
          </div>
          
          <div class="col-md-4 p-2" data-aos="flip-right">
              <div class="rounded m-1 bg-white">
                  <h4>Desserts</h4>
                  <img src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570113037/food/dessert_k2djba.jpg" class="img-fluid rounded-circle m-2 w-50" style="box-shadow: 5px 5px 5px #555252;"/>
                  <p style="padding: 20px;">Savourez nos Gâteaux - dessert. Qui dit Gâteaux -
                       dessert dit saveurs et plaisirs gourmands</p>
              </div>
          </div>
  </div>
</section>

</div>

<div class="container-fluid p-4" id="google-map" style="padding-top: 30px">
  <div class="row">
      <div class="col-md-1 mb-4"></div>
    <!-- How to change your own map point
    1. Go to Google Maps
    2. Click on your location point
    3. Click "Share" and choose "Embed map" tab
    4. Copy only URL and paste it within the src="" field below
    --><div class="col-md-4 mb-4 text-justify">
        <br>
        <h4>Notre localisation</h4>
        <p>Nous nous situons à 200 m de l'arrêt du métro Flachet et à 100 m de l'arrêt de bus c26</p>
        <p>Vous pouvez nous appeler au numéro 07 81 05 76 04 pour commander</p>

      </div>
      <div class="col-md-6 mb-4 pt-4">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1391.4732141096401!2d4.878310658069345!3d45.77226386565072!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDXCsDQ2JzIwLjEiTiA0wrA1Mic0NS45IkU!5e0!3m2!1sfr!2sfr!4v1563445380037!5m2!1sfr!2sfr"
        width="100%" height="350" frameborder="0" style="border:0; box-shadow: 5px 5px 5px #888888;" allowfullscreen></iframe>
      </div>
  </div>
</div> 

{% endblock %}

food/templates/food/pizza.html
{% extends 'food/base.html' %}

{% block title %}Pizzas{% endblock %}

{% block content %}

{% load cloudinary %}

<div id="demo" class="carousel slide" data-ride="carousel" style="box-shadow: 0px 5px 10px">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://res.cloudinary.com/dxflxf2nv/image/upload/v1570464856/food/pizzas_fhsdkj.jpg" alt="slider1">
        <div class="carousel-caption">
          <h3 style="color: whitesmoke;">Majin Burgers</h3>
          <p>Nos Pizzas</p>
        </div>   
      </div>
    </div>
</div>
<div class="container p-4">
  <h2 class="text-center">~ Nos Pizzas ~</h2>
  <h4 class="text-center pb-2" style="color: rgb(43, 41, 41)">⊰ ∼∼.∼∼ ⊱</h4>

  
  <div class="row pt-4">
      {% for pizza in pizzas %}
    <div class="col-xs-12 col-sm-6 col-md-4" data-aos="zoom-in">
        <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
            <div class="mainflip p-3">
                <div class="frontside">
                    <div class="card">
                        <div class="card-body text-center">
                            <p><img class=" img-fluid" src='{{ pizza.pimage.url }}' alt="card image"></p>
                            <h4 class="card-title">{{ pizza.nom }}</h4>
                            <p class="card-text">{{ pizza.descf }}</p>
                            <h5>M: {{ pizza.prixm }} €  L: {{ pizza.prixl }} €</h5>
                        </div>
                    </div>
                </div>
                <div class="backside p-3">
                    <div class="card">
                        <div class="card-body text-center">
                            <h4 class="card-title">{{ pizza.nom }}</h4>
                            <p class="card-text">{{ pizza.descb }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  {% endfor %}
  </div>
  
</div>

{% endblock %}